[project]
name = ""
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aio-pika>=9.5.5",
    "aiolimiter>=1.2.1",
    "asyncpg>=0.30.0",
    "cachier>=4.1.0",
    "colorlog>=6.9.0",
    "dnspython>=2.7.0",
    "fastapi>=0.115.12",
    "faststream[cli,confluent,rabbit,redis]>=0.5.39",
    "funcy>=2.0",
    "glom>=24.11.0",
    "httpx>=0.28.1",
    "inflect>=7.5.0",
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
    "motor>=3.7.0",
    "ollama>=0.5.3",
    "orjson>=3.10.18",
    "phonenumbers>=9.0.2",
    "pika>=1.3.2",
    "plumbum>=1.9.0",
    "psycopg[binary,pool]>=3.2.6",
    "py-cachify>=2.0.10",
    "pydantic-settings>=2.8.1",
    "pydantic[email]>=2.11.2",
    "pydash>=8.0.5",
    "pymongo>=4.11.3",
    "python-dateutil>=2.9.0.post0",
    "python-levenshtein>=0.27.1",
    "python-socketio>=5.13.0",
    "pytz>=2025.2",
    "qdrant-client[fastembed]>=1.15.1",
    "redis>=5.2.1",
    "taskiq-aio-pika>=0.4.2",
    "taskiq-faststream[kafka,rabbit,redis]>=0.2.0",
    "taskiq-redis>=1.0.8",
    "uvicorn>=0.34.2",
]



[dependency-groups]
dev = [
    "icecream>=2.1.5",
    "ipython>=9.4.0",
    "mypy>=1.17.1",
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.5",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.mypy]
python_version = "3.13"
mypy_path = "src"
strict = true
pretty = true
show_error_codes = true
disallow_untyped_calls = true
disallow_untyped_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
implicit_optional = false
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
show_error_context = true
show_column_numbers = true
ignore_missing_imports = true
show_error_code_links = true
color_output = true
show_absolute_path = true
plugins = ["returns.contrib.mypy.returns_plugin"]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "build/",
    "dist/",
    "venv/",
    "\\.venv/",
    "tests/helpers/"
]


[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
line-length = 88
indent-width = 4



[tool.ruff.lint]
allowed-confusables = ["−", "ρ", "∗"]
fixable = ["ALL"]
ignore = []
select = ["E4", "E7", "E9", "F", "B", "Q"]
unfixable = []



[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401", "E402", "F403"]
"**/{tests,docs,tools}/*" = ["E402", "F403"]
[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint.pydocstyle]
convention = "google"


[tool.pytest.ini_options]
addopts = "--cov=src--cov-report=term-missing"



[tool.ty.rules]
unresolved-reference = "ignore"
unresolved-attribute = "ignore"
possibly-unbound-attribute = "ignore"
invalid-return-type = "ignore"
invalid-assignment = "ignore"
unresolved-import = "ignore"
invalid-argument-type = "ignore"
invalid-type-form = "ignore"
no-matching-overload = "ignore"
missing-argument = "ignore"


